spring.datasource.url=jdbc:mysql://localhost:3306/filmtokio?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

api.client.username=user
api.client.password=pass

app.security.jwt.secret=CucurellaCucurellaSeComeUnaPaella
app.security.jwt.expiration=3600

server.port=8081